version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ../backend:/var/www
    depends_on:
      - database
    networks:
      - laravel

  webserver:
    image: nginx:latest
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ../backend:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  database:
    image: mysql:8
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: binome
    ports:
      - "9090:3306"
    volumes:
      - ../database/binome:/var/lib/mysql
    networks:
      - laravel

  #mailhog:
  #  image: mailhog/mailhog
  #  container_name: laravel_mailhog
  #  ports:
  #    - "8025:8025"
  #  networks:
  #    - laravel

networks:
  laravel:
    driver: bridge
