version: '3.8'

services:

  database:
    image: mysql:8
    container_name: binome_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: binome
    ports:
      - "9090:3306"
    volumes:
      - ./database/binome:/var/lib/mysql
    networks:
      - laravel


networks:
  laravel:
    driver: bridge
